version: "3.8"
services:
  sdlc:
    container_name: $LEGEND_SDLC_SERVICE_NAME
    image: finos/legend-sdlc-server:$LEGEND_SDLC_IMAGE_VERSION
    ports:
      - $LEGEND_SDLC_PORT:$LEGEND_SDLC_PORT
    networks:
      - legend
    volumes:
      - $BUILD_DIR/ssl:/ssl
      - $BUILD_DIR/generated-configs/sdlc:/config
      - $BUILD_DIR/generated-configs/gitlab:/gitlab-config
      - $BUILD_DIR/scripts:/scripts
      - $BUILD_DIR/templates/sdlc:/templates
    env_file:
      - $BUILD_DIR/.env
    command: /scripts/run-sdlc.sh

  engine:
    container_name: $LEGEND_ENGINE_SERVICE_NAME
    image: finos/legend-engine-server:$LEGEND_ENGINE_IMAGE_VERSION
    ports:
      - $LEGEND_ENGINE_PORT:$LEGEND_ENGINE_PORT
    networks:
      - legend
    volumes:
      - $BUILD_DIR/ssl:/ssl
      - $BUILD_DIR/generated-configs/engine:/config
      - $BUILD_DIR/generated-configs/gitlab:/gitlab-config
      - $BUILD_DIR/scripts:/scripts
      - $BUILD_DIR/templates/engine:/templates
    env_file:
      - $BUILD_DIR/.env
    command: /scripts/run-engine.sh

networks:
  legend: {}
